name: Java ci/cd with Gradle

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with: 
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          arguments: build

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gsample01 .

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gsample01

  deploy:
    needs: build
    name: deploy
    runs-on: [self-hosted, label-1]
    steps:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker run
        run: |
          docker stop gs01 && docker rm gs01 && docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/gsample01:latest
          docker run -d --name gs01 -p 50005:50005 ${{ secrets.DOCKERHUB_USERNAME }}/gsample01:latest
