name: Java ci/cd with Gradle and Docker

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/gsample01
  CONTAINER: gs01

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with: 
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          arguments: build

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE }} .

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ env.IMAGE }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.IMAGE }}

  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, label-1]
    steps:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ env.IMAGE }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Stop and remove existing container
        run: |
          docker stop gs01 || true
          docker rm gs01 || true
          docker rmi ${{ env.IMAGE }}:latest || true

      - name: Run Docker container
        run: |
          docker run -d --name gs01 -p 50005:50005 ${{ env.IMAGE }}:latest
